apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  annotations:
    association.k8s.elastic.co/es-conf: '{"authSecretName":"kibana-kibana-user","authSecretKey":"token","isApiKey":false,"isServiceAccount":true,"caCertProvided":true,"caSecretName":"kibana-kb-es-ca","url":"https://elasticsearch-es-http.elastic.svc:9200","version":"9.2.4"}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kibana.k8s.elastic.co/v1","kind":"Kibana","metadata":{"annotations":{},"name":"kibana","namespace":"elastic"},"spec":{"count":1,"elasticsearchRef":{"name":"elasticsearch"},"version":"9.2.4"}}
  creationTimestamp: "2026-05-02T10:09:59Z"
  generation: 2
  name: kibana
  namespace: elastic
  resourceVersion: "16037"
  uid: a548e0c4-7036-4387-b047-3235702bfc6b
spec:
  count: 1
  elasticsearchRef:
    name: elasticsearch
  enterpriseSearchRef: {}
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
  monitoring:
    logs: {}
    metrics: {}
  podTemplate:
    metadata: {}
    spec:
      containers: null
  version: 9.2.4
status:
  associationStatus: Established
  availableNodes: 1
  count: 1
  elasticsearchAssociationStatus: Established
  health: green
  observedGeneration: 2
  selector: common.k8s.elastic.co/type=kibana,kibana.k8s.elastic.co/name=kibana
  version: 9.2.4
