include:
- bluesky-harvester.zip
kind: ArchiveUploadSpec
name: bluesky-harvester-zip-HCpw

---
apiVersion: fission.io/v1
kind: Package
metadata:
  name: bluesky-pkg
spec:
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://bluesky-harvester-zip-HCpw
status:
  buildstatus: pending
  lastUpdateTimestamp: "2026-05-06T11:52:03Z"
